本节课对数据输入及转化介绍

# 1. CSV, SQL, PQRQUEL, JSON, XML, HTML, Excel, 等数据格式的输入及转化

# 2. 对图片数据进行输入及转化

# 3. 对文本数据进行输入及转化

# 4. 对时间序列数据进行输入及转化


# 一、复习

1.torch矢量生成及修改维度
练习：
1）使用标准正态分布随机生成一个$2\times 3\times 4$的张量，并修改其维度为$3\times 8$。
2）使用均匀分布随机生成一个$2\times 3\times 4$的张量，并修改其维度为$3\times 8$。
3）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请修改其维度为$2\times 3\times 4$。
4) 已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请生成一个与其维度一致的全1张量。


2.torch张量索引
练习：
1）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请取出第2行第3列的元素。
2）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请取出第2行第3列的元素，并修改其值为100。

3. torch张量切片
练习：
1）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请取出第2行第3列的元素。
2）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请取出第2行的元素。

4. torch张量拼接
练习：
1）已知tensor1=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，tensor2=torch.tensor([[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])，请将两个张量拼接在一起。
2）已知tensor1=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，tensor2=torch.tensor([[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])，请将两个张量按照行拼接在一起。

5. torch张量运算
练习：
1）已知tensor1=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，tensor2=torch.tensor([[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])，请计算两个张量的和。
2）已知tensor1=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，tensor2=torch.tensor([[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])，请计算两个张量的乘积。
3）已知tensor1=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，tensor2=torch.tensor([[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])，请计算两个张量的点积。

6. torch张量统计
练习：
1）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请计算张量的均值。
2）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请计算张量的最大值。
3）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请计算张量的最小值。
4）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请计算张量的方差。
5）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请计算张量的标准差。

7. torch张量排序
1）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请对张量进行排序。
2）已知tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])，请对张量进行逆序排序。

8. torch张量求导    
1） 已知张量x=torch.tensor([1,2,3,4,5],requires_grad=True)，请计算x的平方和的导数。
2） 已知张量x=torch.tensor([1,2,3,4,5],requires_grad=True)，请计算x的立方和的导数。
3） 已知张量y=2x^3+3x^2+4x+5，请计算y对x的导数。
4） 已知张量y=2x^3+3x^2+4x+5，请计算y对x的二阶导数。







## 习题作答

In [1]:
import torch

In [19]:
# pytorch生产标准正态分布
def normal(shape):
    data = torch.randn(shape)
    return data

# pytorch生成均匀分布
def uniform(shape):
    data = torch.rand(shape)
    return data

# 修改维度
def re_shape(data,shape):
    return data.view(shape)

### 1

In [27]:
d1_1.view([3,8])

tensor([[ 0.9420,  0.0213, -0.7815,  0.6887, -0.8215,  1.4396,  0.6597,  1.2506],
        [ 0.8012, -1.0815, -1.3436, -0.6533, -3.0046,  0.4208, -0.3891,  1.2633],
        [-0.0866,  0.3465,  0.4803,  1.1210, -1.2786,  0.5436, -1.0626, -1.5050]])

In [54]:
d1_1 = normal([2,3,4])
d1_1_ = re_shape(d1_1,[3,8])
print(d1_1.size())
print(d1_1_.size())
print()
d1_2 = uniform([2,3,4])
d1_2_ = re_shape(d1_2_,[3,8])
print(d1_2.size())
print(d1_2_.size())
print()
tensor = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
tt = tensor.view(3,4)
print(tt.size())
print()
tensor = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
tt = torch.ones_like(tensor)
print(tt.size())

torch.Size([2, 3, 4])
torch.Size([3, 8])

torch.Size([2, 3, 4])
torch.Size([3, 8])

torch.Size([3, 4])

torch.Size([3, 4])


### 2

In [55]:
tensor = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(tensor[0,1,2])

tensor[0,1,2]=100
print(tensor)

tensor(7)
tensor([[[  1,   2,   3,   4],
         [  5,   6, 100,   8],
         [  9,  10,  11,  12]]])


### 3

In [61]:
tensor = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(tensor[0,1,2])
tensor = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print('第二行：',tensor[0,1,:])
print("第三列：",tensor[0,:,2])

tensor(7)
第二行： tensor([5, 6, 7, 8])
第三列： tensor([ 3,  7, 11])


### 4

In [67]:
tensor1=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
tensor2=torch.tensor([[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print("按行拼接：\n",torch.cat((tensor1,tensor2)))
print('按列拼接：\n',torch.cat((tensor1,tensor2),dim=1))

按行拼接：
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
按列拼接：
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


### 5

In [83]:
tensor1=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
tensor2=torch.tensor([[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print("两个张量的和:\n",tensor1+tensor2)
print("两个张量的乘积:\n",tensor1*tensor2)
print("两个张量沿着第 2 维度的点积:\n",torch.tensordot(tensor1, tensor2, dims=([2], [2])))

两个张量的和:
 tensor([[[14, 16, 18, 20],
         [22, 24, 26, 28],
         [30, 32, 34, 36]]])
两个张量的乘积:
 tensor([[[ 13,  28,  45,  64],
         [ 85, 108, 133, 160],
         [189, 220, 253, 288]]])
两个张量沿着第 2 维度的点积:
 tensor([[[[150, 190, 230]],

         [[382, 486, 590]],

         [[614, 782, 950]]]])


### 6

In [93]:
tensor1=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
tensor2=torch.tensor([[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print('tensor1的均值:',torch.mean(tensor1.float()))
print('tensor2的均值:',torch.mean(tensor2.float()))
tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print('tensor最大值：',torch.max(tensor))
print('tensor最小值：',torch.min(tensor))
print('tensor方差：',torch.var(tensor.float()))
print('tensor的标准差：',torch.std(tensor.float()))

tensor1的均值: tensor(6.5000)
tensor2的均值: tensor(18.5000)
tensor最大值： tensor(12)
tensor最小值： tensor(1)
tensor方差： tensor(13.)
tensor的标准差： tensor(3.6056)


### 7

In [103]:
tensor=torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print('排序后的tensor：\n',torch.sort(tensor)[0])
print('按行逆序排序后的tensor：\n',torch.sort(tensor,descending=True)[0])
print('按列逆序排序后的tensor：\n',torch.sort(tensor,descending=True,dim=1)[0])

排序后的tensor：
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])
按行逆序排序后的tensor：
 tensor([[[ 4,  3,  2,  1],
         [ 8,  7,  6,  5],
         [12, 11, 10,  9]]])
按列逆序排序后的tensor：
 tensor([[[ 9, 10, 11, 12],
         [ 5,  6,  7,  8],
         [ 1,  2,  3,  4]]])


### 8


In [113]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0], requires_grad=True)
f = torch.sum(x**2)
f.backward()
print('x的平方和的导数：\n',x.grad)
z = torch.sum(x**3)
z.backward()
print('x的立方和的导数：\n',x.grad)
y = 2*x**2+3*x**2+4*x+5
h = y.sum()
h.backward()
print(x.grad)

x的平方和的导数：
 tensor([ 2.,  4.,  6.,  8., 10.])
x的立方和的导数：
 tensor([ 5., 16., 33., 56., 85.])
tensor([ 19.,  40.,  67., 100., 139.])
